# Currently behind a firewall and not available for the public.
# Uses the nginx/jwilder proxy to link to the correct docker container.
social_nightly_web:
  image: goalgorilla/drupal_social
  links:
    - social_nightly_db:db
  ports:
    - "80"
  environment:
    - VIRTUAL_HOST=nightly_build.socialci.goalgorilla.com
  volumes:
   - /root/drupal_social/social-jenkins-data/workspace/nightly_build:/root/dev-scripts

social_nightly_db_data:
  image: mysql:5.6
  environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=social
  container_name: social_nightly_db_data
  command: /bin/true
  volumes:
    - /var/lib/mysql

social_nightly_db:
  image: mysql:5.6
  environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=social
  volumes_from:
    - social_nightly_db_data


