version: "2"

services:
  web_scripts:
    build: docker_build/drupal8/travis
    volumes:
     - ./public_html:/var/www/html
     - ./dev-scripts/:/root/dev-scripts
     - ./docker_build/drupal8/travis/:/root/travis
     - ./test-results/:/root/test-results
    network_mode: "bridge"

  web:
    image: goalgorilla/drupal_social
    volumes:
     - ./public_html:/var/www/html
    links:
     - db:db
    ports:
     - "80"
    network_mode: "bridge"

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=social
    volumes:
     - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    network_mode: "bridge"

  selenium:
    image: selenium/standalone-firefox
    links:
     - web:web
    ports:
     - "4444"
     - "5900"
    container_name: social_selenium
    cap_add:
     - NET_ADMIN
     - NET_RAW
    network_mode: "bridge"

  behat:
    build: docker_build/drupal8/travis
    container_name: social_behat
    volumes:
     - ./public_html/:/var/www/html
     - ./dev-scripts/:/root/dev-scripts
     - ./behat/:/root/behat
     - ./docker_build/drupal8/travis/:/root/travis
    links:
     - web:web
     - db:db
     - selenium:selenium
    network_mode: "bridge"

volumes:
  db_data:
