# Schema for the configuration files of the group module.

group.settings:
  type: 'config_object'
  label: 'Group settings'
  mapping:
    use_admin_theme:
      type: 'boolean'
      label: 'Use admin theme when editing or creating groups'

group.type.*:
  type: 'config_entity'
  label: 'Group type'
  mapping:
    id:
      type: 'string'
      label: 'Machine-readable name'
    label:
      type: 'label'
      label: 'Label'
    description:
      type: 'text'
      label: 'Description'
    content:
      type: 'sequence'
      label: 'Group content enabler plugins'
      sequence:
        type: 'mapping'
        label: 'Group content plugin configuration'
        mapping:
          id:
            type: 'string'
            label: 'Plugin ID'
          group_type:
            type: 'string'
            label: 'Group type ID'
          data:
            type: 'sequence'
            label: 'Plugin configuration'

# Follows the pattern group.role.GROUP_TYPE_ID-GROUP_ROLE_ID.
group.role.*:
  type: 'config_entity'
  label: 'Group role'
  mapping:
    id:
      type: 'string'
      label: 'Machine-readable name'
    label:
      type: 'label'
      label: 'Label'
    weight:
      type: 'integer'
      label: 'Weight'
    internal:
      type: 'boolean'
      label: 'Group role is used internally'
    group_type:
      type: 'string'
      label: 'Group type ID'
    permissions:
      type: 'sequence'
      label: 'Permissions'
      sequence:
        type: 'string'
        label: 'Group permission'

group_content_type:
  type: 'config_entity'
  label: 'Group content type'
  mapping:
    id:
      type: 'string'
      label: 'Machine-readable name'
    label:
      type: 'label'
      label: 'Label'
    description:
      type: 'text'
      label: 'Description'
    group_type:
      type: 'text'
      label: 'Group type ID'
    content_plugin:
      type: 'text'
      label: 'Group content plugin ID'

# Follows the pattern group.content_type.GROUP_TYPE_ID-PLUGIN_ID.
# Follows the pattern group.content_type.GROUP_TYPE_ID-PLUGIN_ID-DERIVATIVE_ID.
group.content_type.*:
  type: 'group_content_type'
  label: 'Group content type'

entity_reference_selection.group_type:group_role:
  type: 'entity_reference_selection'
  mapping:
    group_type_id:
      type: 'string'
      label: 'The group type to check for available roles.'
