default:
  autoload:
    '': /root/behat/features/bootstrap
  suites:
    default:
      parameters:
        test_users:
          admin:
            username: 'admin'
            password: 'admin'
            mail: 'info+admin@example.com'
      paths:
        features: '/root/behat/features'
        bootstrap: '/root/behat/features/bootstrap'
      contexts:
        - FeatureContext
        - SocialDrupalContext
        - SocialMinkContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MessageContext
        - PostContext
  extensions:
      Behat\MinkExtension:
        default_session: 'selenium2'
        base_url: 'http://web/'
        files_path: '/root/files/'
        goutte: ~
        selenium2:
          wd_host: 'http://selenium:4444/wd/hub/'
          browser: 'firefox'
      Drupal\DrupalExtension:
        api_driver: 'drupal'
        drupal:
          drupal_root: '/var/www/html'
        selectors:
          message_selector: '.alert'
          error_message_selector: '.alert.alert-danger'
          success_message_selector: '.alert.alert-success'
        text:
          username_field: 'Username or email address'
          log_in: "Log in"
          log_out: "Logout"
        region_map:
          'Page title block': '.section-title'
          'Hero block': '.cover'
          'Main content': '#content'
          'Main content front': '.col-sm-8'
          'Sidebar second': 'div[role=complementary]'
