social_geolocation.settings:
  type: config_object
  label: 'Social Geolocation settings'
  mapping:
    site_manager_contact:
      type: integer
      label: 'The User ID of the site manager that can be contacted in case of a geolocation error'
    geolocation_provider:
      type: string
      label: 'The choice for which provider to use to store geolocation data'
