core.entity_view_display.node.book.hero:
  expected_config:
    content:
      field_book_image:
        label: above
  update_actions:
    change:
      content:
        field_book_image:
          label: hidden
