plugin.plugin_configuration.facets_processor.count_widget_widget_order:
  type: mapping
  label: 'Count widget order'
  mapping:
    sort:
      type: string
      label: sort order

plugin.plugin_configuration.facets_processor.display_value_widget_order:
  type: mapping
  label: 'Display value widget order'
  mapping:
    sort:
      type: string
      label: sort order

plugin.plugin_configuration.facets_processor.exclude_specified_items:
  type: mapping
  label: 'Exclude specified items'
  mapping:
    exclude:
      type: string
      label: Exclude
    regex:
      type: boolean
      label: Regex

plugin.plugin_configuration.facets_processor.raw_value_widget_order:
  type: mapping
  label: 'Raw value widget order'
  mapping:
    sort:
      type: string
      label: sort order

plugin.plugin_configuration.facets_processor.active_widget_order:
  type: mapping
  label: 'Active widget order'
  mapping:
    sort:
      type: string
      label: sort order

plugin.plugin_configuration.facets_processor.count_widget_order:
  type: mapping
  label: 'Active widget order'
  mapping:
    sort:
      type: string
      label: sort order

plugin.plugin_configuration.facets_processor.count_limit:
  type: mapping
  label: 'Count limit widget'
  mapping:
    minimum_items:
      type: integer
      label: 'Mimimum amount of items to show.'
    maximum_items:
      type: integer
      label: 'Maximum amount of items to show.'

plugin.plugin_configuration.facets_processor.url_processor_handler:
  type: config_object

plugin.plugin_configuration.facets_processor.hide_non_narrowing_result_processor:
  type: config_object

plugin.plugin_configuration.facets_processor.hide_active_items_processor:
  type: config_object
