core.entity_view_display.profile.profile.small_teaser:
  expected_config:
    content:
      field_profile_image:
        settings:
          image_style: social_small
    hidden:
      field_profile_function: true
      field_profile_organization: true
  update_actions:
    add:
      content:
        field_profile_function:
          label: hidden
          region: content
          settings:
            link_to_entity: false
          third_party_settings: {  }
          type: string
          weight: 1
        field_profile_organization:
          label: hidden
          region: content
          settings:
            link_to_entity: false
          third_party_settings: {  }
          type: string
          weight: 2
    change:
      content:
        field_profile_image:
          settings:
            image_style: social_medium
      hidden:
        field_profile_nick_name: true
        field_profile_organization_tag: true
