message.template.user_was_enrolled_to_event:
  expected_config:
    text:
      2:
        value: "<p>This is to confirm that you've enrolled for the event <em>[social_event:event_iam_organizing]</em>.</p>\r\n\r\n<p>[message:preview]</p>\r\n\r\n<p>[message:cta_button]</p>\r\n"
  update_actions:
    delete:
      text: { }
    add:
      text:
        0:
          value: "<p>This is to confirm that you've enrolled for the event <em>[social_event:event_iam_organizing]</em>.</p>\r\n\r\n<p>[message:preview]</p>\r\n\r\n<p>[message:cta_button]</p>\r\n"
          format: full_html
        1:
          value: "<p>This is to confirm that you've enrolled for the event <em>[social_event:event_iam_organizing]</em>.</p>\r\n\r\n<p>[message:preview]</p>\r\n\r\n<p>[message:cta_button]</p>\r\n"
          format: full_html
        2:
          value: "<p>This is to confirm that you've enrolled for the event <em>[social_event:event_iam_organizing]</em>.</p>\r\n\r\n<p>[message:preview]</p>\r\n\r\n<p>[message:cta_button]</p>\r\n"
          format: full_html
