block.block.socialbase_local_tasks:
  expected_config:
    visibility:
      request_path:
        pages: "post/*/edit\r\npost/*/delete\r\n/post/*/edit\r\n/post/*/delete"
  update_actions:
    change:
      visibility:
        request_path:
          pages: "/post/*/edit\r\n/post/*/delete\r\n/user/*/edit\r\n/user/*/profile\r\n/group/*/edit"
block.block.socialblue_local_tasks:
  expected_config:
    visibility:
      request_path:
        pages: "post/*/edit\r\npost/*/delete\r\n/post/*/edit\r\n/post/*/delete\r\n/user/*/edit\r\n/group/*/edit"
  update_actions:
    change:
      visibility:
        request_path:
          pages: "/post/*/edit\r\n/post/*/delete\r\n/user/*/edit\r\n/user/*/profile\r\n/group/*/edit"
