core.entity_view_display.profile.profile.teaser:
  expected_config: { }
  update_actions:
    add:
      content:
        followers:
          weight: 5
          region: content
          settings: {  }
          third_party_settings: {  }
        following:
          weight: 6
          region: content
          settings: {  }
          third_party_settings: {  }
core.entity_view_display.profile.profile.statistic:
  expected_config: { }
  update_actions:
    add:
      content:
        followers:
          weight: 5
          region: content
          settings: {  }
          third_party_settings: {  }
        following:
          weight: 6
          region: content
          settings: {  }
          third_party_settings: {  }
