# Schema for the configuration files of the Social Content Report module.
social_content_report.settings:
  type: config_object
  label: 'Social Content Moderation settings'
  mapping:
    unpublish_threshold:
      type: boolean
      label: 'Whether the content is immediately unpublished if a user reports it as inappropriate.'
    reasons_with_text:
      type: sequence
      sequence:
        type: integer
        label: 'Reason term for which an additional textfield is displayed.'
    mandatory_reason:
      type: integer
      label: 'Whether a reason is mandatory when reporting inappropriate content.'
