social_swiftmail.settings:
  type: config_object
  label: 'Social Swiftmail Settings'
  mapping:
    remove_open_social_branding:
      type: boolean
      label: 'Open Social Branding will be replaced by site name (and slogan if available).'
    template_header:
      type: mapping
      label: 'Template header'
      mapping:
        value:
          type: text
          label: 'Header markup'
        format:
          type: string
          label: 'Text format'
    template_footer:
      type: mapping
      label: 'Template footer'
      mapping:
        value:
          type: text
          label: 'Footer markup'
        format:
          type: string
          label: 'Text format'
    do_not_send_emails_new_users:
      type: boolean
      label: "Don't send email notifications to users who have never logged in"
