social_lets_connect_usage.usage_data:
  type: sequence
  sequence:
    - type: string
    - label: 'Usage data shared with Open Social team'

social_lets_connect_usage.refresh_interval:
  type: integer
  label: 'Refresh interval in seconds'

social_lets_connect_usage.url:
  type: string
  label: 'URL to send the usage data to'
