core.entity_view_display.node.topic.small_teaser:
  expected_config:
    content:
      flag_follow_content:
        region: content
        weight: 10
    hidden:
      field_topic_image: true
  update_actions:
    add:
      hidden:
        flag_follow_content: true
        groups_type_flexible_group: true
        social_tagging: true
    change:
      content:
        field_topic_image:
          label: hidden
          region: content
          settings:
            image_link: content
            image_style: social_medium
          third_party_settings: {  }
          type: image
          weight: 0
    delete:
      content:
        flag_follow_content:
          region: content
          weight: 10
      hidden:
        field_topic_image: true
