name: 'Behat'

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request: { }

# github.head_ref is only set when the workflow was triggered by a pull_request and it contains the value of the source branch of the PR.
# github.ref_name will than only be used if the workflow was not triggered by a pull_request and it also just contains the branch name.
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Running tests"
  tests:
    name: Stability 3
    runs-on: ubuntu-22.04
    steps:
      # Set PHP version to 8.0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none # disable xdebug, pcov
          tools: cs2pr

      # We want to reuse our project setup to run different jobs at once.
      - uses: actions/cache@v3
        id: opensocial-project-build
        with:
          path: ./*
          key: ${{ github.sha }}

      # Checkout Drupal Social.
      - uses: actions/checkout@v3
        with:
          repository: 'goalgorilla/drupal_social'
          ref: '5.3.0'

      # Install the version of Open Social under test.
      - name: Composer require current branch
        run: composer require goalgorilla/open_social:dev-$BRANCH_NAME

      # Install the docker.
      - name: Install Docker
        run: sh scripts/social/ci/install-docker.sh

      - name: Run Docker containers
        run: docker-compose -f docker-compose-ci.yml up -d

      - name: Install Open Social
        run: docker exec -i social_ci_web bash /var/www/scripts/social/install/install_script.sh --with-optional --localsettings

      - name: Run Integration tests
        run: docker exec -i social_ci_behat bash /var/www/scripts/social/behatstability.sh "stability-3 --stop-on-failure --strict  --colors"
