#name: 'Behat'
#
## Controls when the workflow will run
#on:
#  pull_request:
#    # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-object-35
#    types: [ ready_for_review, reopened, synchronize ]
#
## github.head_ref is only set when the workflow was triggered by a pull_request and it contains the value of the source branch of the PR.
## github.ref_name will than only be used if the workflow was not triggered by a pull_request and it also just contains the branch name.
#env:
#  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
#
## A workflow run is made up of one or more jobs that can run sequentially or in parallel
#jobs:
#  # This workflow contains a single job called "Running tests"
#  tests:
#    name: 'Upgrade Path'
#    if: ${{ !github.event.pull_request.draft }}
#    runs-on: ubuntu-22.04
#    steps:
#      # Setup PHP 7.4
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: 7.4
#          coverage: none # disable xdebug, pcov
#          tools: cs2pr
#
#      # Checkout Drupal Social.
#      - uses: actions/checkout@v3
#        with:
#          repository: 'goalgorilla/drupal_social'
#          ref: 'upgrade-path'
#          fetch-depth: 0
#
#      # Set php memory limit to -1 so composer update will not fail
#      # Enforce throwing an error and stopping package installation/update immediately
#      - name: Set composer configurations
#        run: |
#          export COMPOSER_MEMORY_LIMIT=-1
#          export COMPOSER_EXIT_ON_PATCH_FAILURE=1
#
#      # Remove roave/security-advisories depdendency as it conflicts with drupal/core:~8.9.9 requirements in our update branch. See: https://github.com/Roave/SecurityAdvisories/commit/5bd8c4f672d819d073ca8de1922fdb6898d0df3a
#      - name: Remove roave/security-advisories from composer.json
#        run: composer remove roave/security-advisories --no-update
#
#      # 8.x-8.x-composer-update-to-10-branch has some composer breaking changes for scaffolding, we couldn't release but helps us with testing our update path.
#      - name: Install update branch of Open Social
#        run: composer require goalgorilla/open_social:dev-8.x-8.x-composer-update-to-10-branch --prefer-dist
#
#      # Install the docker.
#      - name: Install Docker
#        run: sh scripts/social/ci/install-docker.sh
#
#      - name: Run Docker containers
#        run: docker-compose -f docker-compose-ci.yml up -d
#
#      # Install Open Social
#      - name: Install Open Social
#        run: docker exec -i social_ci_web bash /var/www/scripts/social/install/install_script.sh
#
#      # Reset the entire branch, so we can checkout goalgorilla/drupal_social:5.3.0
#      # and ths way we won't get issues with dev dependencies from 8.x related Open Social versions.
#      - name: Prepare repository for upgrade
#        run: |
#          git stash
#          rm -rf vendor/ composer.lock
#          git checkout 5.3.0
#
#      - name: Composer require current branch and social_search_autocomplete
#        run: |
#          docker exec -i social_ci_web  composer require goalgorilla/open_social:dev-$BRANCH_NAME --update-with-all-dependencies
#          docker exec -i social_ci_web  composer require drupal/social_search_autocomplete
#
#      # Restore the correct permissions for these folders as they get lost after above steps.
#      - name: Add correct permissions to vendor and html folder.
#        run: docker exec -i social_ci_web chown -R www-data:www-data vendor/ html/
#
#      # Execute the updates.
#      - name: Run the updates
#        run: docker exec -i social_ci_web bash /var/www/scripts/social/install/update.sh
#
#      # Run the upgrade path behat tests
#      - name: Run Integration tests
#        run: docker exec -i social_ci_behat sh /var/www/scripts/social/behatstability.sh "stability-1&&~DS-1136&&~DS-3605 --stop-on-failure --strict  --colors"
